### ISSUE TITLE
Enstops

### ISSUE THREAD

**Issue by alxtr1bal** [Guilouz/Marlin-Sidewinder-X1-SKR2.0#4]
Hello there, thanks for this configuration for the SW X1. Following the diagram, i manage to install the new board (with TMC2209 steppers in UART mode).

Unfortunately, something is wrong for me : none of the endstops are working anymore...

Do you have an idea ?

**Comment by Guilouz** [comment]
Can you be more explicit please ? What return M119 command ?

**Comment by alxtr1bal** [comment]
The M119 shows open for each endstop, even if triggered.

**Comment by alxtr1bal** [comment]
Hmmm wait , i may have done something wrong, as i disabled the bltouch (as i don't have one).

**Comment by alxtr1bal** [comment]
Yep, sorry :) wrong setup on my side after disabling bltouch 
My bad !
Closing this.
