### ISSUE TITLE
Problem homing Z avec probe

### ISSUE THREAD

**Issue by kasuke5** [Guilouz/Marlin-Sidewinder-X1-SKR2.0#5]
Je ne sais pas si ça fait ça avec d'autre mais j'ai souvent un soucis quand l'axe Z doit se régler.
Parfois, et c'est bien souvent juste après un homing du Z, quand on refait le homing du Z, ça descend pas jusqu'au bout et l'imprimante se met en erreur.
Cas concret, je règle le réglage d'extruder sur le menu, ça fonctionne, je remets une valeure donc je relance le test, la l'imprimante au moment de régler le Z ne va pas jusqu'au bout et se met en halt.
J'ai pris le dernier firmware en date sans rien modifier dessus, j'utilise les branchements du waggster mod.

**Comment by Urufu87** [comment]
j'ai le même problème, avez vous pu trouver une solution ?

**Comment by Urufu87** [comment]
> Je ne sais pas si ça fait ça avec d'autre mais j'ai souvent un soucis quand l'axe Z doit se régler.
> Parfois, et c'est bien souvent juste après un homing du Z, quand on refait le homing du Z, ça down pas jusqu'au bout et l'imprimante se met en erreur.
> Cas concret, je règle le réglage d'extruder sur le menu, ça fonctionne, je remets une valeure donc je relance le test, la l'imprimante au moment de régler le Z ne va pas jusqu'au bout et se met en halt.
> J'ai pris le dernier firmware en date sans rien modificatore dessus, j'utilise les branchements du waggster mod.



> Je ne sais pas si ça fait ça avec d'autre mais j'ai souvent un soucis quand l'axe Z doit se régler.
> Parfois, et c'est bien souvent juste après un homing du Z, quand on refait le homing du Z, ça down pas jusqu'au bout et l'imprimante se met en erreur.
> Cas concret, je règle le réglage d'extruder sur le menu, ça fonctionne, je remets une valeure donc je relance le test, la l'imprimante au moment de régler le Z ne va pas jusqu'au bout et se met en halt.
> J'ai pris le dernier firmware en date sans rien modificatore dessus, j'utilise les branchements du waggster mod.

j'ai le même problème, avez vous pu trouver une solution ?

**Comment by kasuke5** [comment]
perso non :/

**Comment by Urufu87** [comment]
> numero personale: /

Serait-ce un problème avec le firmware 5v sur la 3d touch ?  Ou un problème sur le E-PCB ?  En ce moment, j'ai changé le câble plat et j'attends un nouveau E-PCB.  Mais je ne trouve toujours pas de solution.

**Comment by kasuke5** [comment]
Je ne sais pas mais j'ai aussi un 3D touch, peut-être ça vient de la ?

**Comment by Urufu87** [comment]
> Je ne sais pas mais j'ai aussi un 3D touch, peut-être ça vient de la ?

J'ai lu sur certains forums que certains clones 3dtouch peuvent avoir le numéro 4 et le numéro 5 inversés... depuis que j'ai renvoyé la carte mère, faites ceci essayez d'inverser les câbles du 3dtouch et faites le moi savoir

**Comment by Urufu87** [comment]
> Je ne sais pas mais j'ai aussi un 3D touch, peut-être ça vient de la ?

Quelques nouvelles?

**Comment by kasuke5** [comment]
Non, j'ai un problème d'extrusion j'attends une nouvelle pièces donc d'ici là, je ne peux pas vraiment tester

**Comment by kasuke5** [comment]
J'ai un nouveau problème, le ventilateur pour refroidir la buse (sur le côté pas en façade) ne veut pas fonctionner, je ne sais pas si j'ai bien réalisé mon câblage et je ne sais pas comment le vérifier puisque tout le reste fonctionne.
Je suis encore bloqué :/

**Comment by kasuke5** [comment]
> 
> 
> > J'ai un nouveau problème, le ventilateur pour refroidir la buse (sur le côté pas en façade) ne veut pas fonctionner, je ne sais pas si j'ai bien réalisé mon câblage et je ne sais pas comment le vérifier puisque tout le reste fonctionne. Je suis encore bloqué :/
> 
> Le ventilateur Hotend doit être branché sur le port HE1 et il se déclenche automatiquement dès que la température de la hotend atteint 50°C.
Oui c'est ce que j'ai fais mais ça ne fonctionne pas, le ventilateur fonctionne bien (je l'ai branché ailleurs pour test)
https://imgur.com/a/E5g01Bd ce qui me perturbe c'est que mon cable rouge (+) est celui que j'ai pointé, et le - le bleu or si le - de ce cable rouge, on voit bien que c'est le cable noir d'a coté, mais l'imprimante ne se connecte pas quand j'interchange le cable noir et le bleu.
Je suis vraiment pas sur du cablage, je n'avais pas noté éxactement la première fois que j'avais changé la carte mère :/
Mais comme tout fonctionne mis à part cela, je ne sais pas ou j'aurais interverti des cables

**Comment by kasuke5** [comment]
Ah ! J'ai résolu le problème ! (de mon extrusion et du ventilateur)
Il me semble pas avoir changé cette ligne dans Configuration_adv.h -> #define E0_AUTO_FAN_PIN PB6
Il fallait que ce soit #define E0_AUTO_FAN_PIN PB4 ... Bref je m'en suis sorti et le je fais des tests, à voir pour le bl touch après

**Comment by kasuke5** [comment]
> 
> 
> @kasuke5 Si tu utilises le PIN PB6 c'est que tu ne l'as pas branché sur HE1 mais sur FAN1

Vu que ça fait un moment que je suis sur la réparation (entre temps j'ai cramé une SKR 2 en voulant changer les vref ... d'un moteur ...Alors que je crois qu'on peut le changer dans le firmware) J'avais surement du le changer je ne sais quand ni pourquoi :/ 
Du coup je me suis entêté à vouloir le mettre sur HE1 alors que ce n'était pas possible.

**Comment by Guilouz** [comment]
> > @kasuke5 Si tu utilises le PIN PB6 c'est que tu ne l'as pas branché sur HE1 mais sur FAN1
> 
> Vu que ça fait un moment que je suis sur la réparation (entre temps j'ai cramé une SKR 2 en voulant changer les vref ... d'un moteur ...Alors que je crois qu'on peut le changer dans le firmware) J'avais surement du le changer je ne sais quand ni pourquoi :/ Du coup je me suis entêté à vouloir le mettre sur HE1 alors que ce n'était pas possible.

Si tes drivers sont configurés en UART (comme c'est le cas sur mon firmware), oui pas besoin de s'occuper des vrefs, les courants sont définis dans Marlin et peuvent être ajustés directement depuis l'écran BTT.

**Comment by Guilouz** [comment]
> Alors j'ai résolu le problème en remettant le Z offset à 0 (il était à -2 et des brouettes) c'est normal que ça réagisse comme ça ?

Oui et non, tu avais surement pas fait de reset EEPROM. Il faut toujours faire un reset EEPROM après flash, pour remettre en place les paramètres et nouveautés d'un firmware.
